public with sharing class Funko_Constants {
    /**
     * Order Summary statuses.
     */
    public static final String ORDERSUMMARY_STATUS_REMORSEPERIODENDED = 'RemorsePeriodEnded';
    public static final String ORDERSUMMARY_STATUS_CREATED = 'Created';

    /**
     * Flow API names.
     */
    public static final String FLOW_CREATE_FULFILLMENTORDER_APINAME = 'Funko_AutoLaunched_CreateFulfillmentOrders';

    /**
     * Flow Variable names.
     */
    public static final String FLOW_CREATE_FULFILLMENTORDER_INPUT_ORDERSUMMARYID_APINAME = 'input_OrderSummryId';
}